### ISSUE TITLE
raise GUI map zoom level

### ISSUE THREAD

**Issue by Sheng-Cheng** [Sheng-Cheng/OpenMACE#3]
In the new GUI interface, can we raise the map's zoom level?

We're running experiments at a 30 m x 90 m field. But it looks too small on the map compared to the drone's icons (see attached snapshot). Is there a way to further zoom in on the map?

![image3721](https://user-images.githubusercontent.com/32967978/104976605-951ef800-59cb-11eb-9589-9a1c91a1a1cc.png)

The following zoom level would be better than the current.
![Screenshot from 2021-01-18 20-35-36](https://user-images.githubusercontent.com/32967978/104977210-fbf0e100-59cc-11eb-9212-696ae257e093.png)

**Comment by patnolan33** [comment]
Fix in #5 . Note that the map tiles are blurry at this zoom level. This is not something we can generally control.
